# Generated by Django 5.1.3 on 2024-11-23 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image_url',
            field=models.URLField(default='https://upload.wikimedia.org/wikipedia/commons/a/ac/No_image_available.svg'),
        ),
    ]
