# Generated by Django 5.1.3 on 2024-11-23 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_product_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productprice',
            name='timestamp',
            field=models.DateTimeField(),
        ),
    ]
