# Generated by Django 5.1.3 on 2024-11-23 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_alter_productprice_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productprice',
            name='timestamp',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
