# Generated by Django 5.1.3 on 2024-11-24 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0004_alter_productprice_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinterest',
            name='notify',
            field=models.BooleanField(default=False),
        ),
    ]
